# Example configuration file for a COLIBRE-like simulation

# Location of the 'observational data' repository and its compiled
# contents (relative to the config)
observational_data_directory: observational_data

# Location of your other .yml files that are passed to the
# velociraptor auto plotter (these describe your scaling)
# relation figures. Also required is the registration file
# in the case where you have non-catalogue properties
# used in the autoplotter.
auto_plotter_directory: auto_plotter
auto_plotter_registration: registration.py

# Style sheet to be used throughout with plotting (stored inside config)
matplotlib_stylesheet: mnras.mplstyle

# Jinja2 template that gets fed the swiftsimio metadata
# object for you to describe the run with (relative to config)
description_template: description.html
# Custom CSS to change the appearance of the webpage 
custom_css: custom.css

# Location and description of additional figures
scripts:
  - filename: scripts/density_temperature.py
    caption: Density-temperature diagram.
    output_file: density_temperature.png
    section: Density-Temperature
    title: Density-Temperature
    additional_args:
      cmap: cividis
      cmap_order: regular